[project]
name = "codegen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "jinja2>=3.1.6",
    "sqlglot>=26.33.0",
]

[dependency-groups]
dev = [
    "ruff>=0.12.5",
]
